### ISSUE TITLE
Layout issues around `<wp-block>` and `display: contents`

### ISSUE THREAD

**Issue by yscik** [WordPress/block-hydration-experiments#49]
Themes commonly style the top-level content elements, like `.entry-content > *`, for layout and spacing, eg to allow various alignments. Example:

```css
.entry-content > :not(.alignwide):not(.alignfull):not(.alignleft):not(.alignright):not(.is-style-wide) {
  max-width: 58rem;
  width: calc(100% - 4rem);
	}
.entry-content > * {
  margin-left: auto;
  margin-right: auto;
  margin-bottom: 1.25em;
}
```
 
This doesn't really work with `display: contents` on the `<wp-block>` wrapper:

|  Current | Expected  |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/176949/183438047-b7087c4e-0fa2-490a-8ce5-bf36ed3b557f.png)  | ![image](https://user-images.githubusercontent.com/176949/183438068-7494b847-6840-40ef-888c-ec16763a5157.png)  |

One option is inheriting these spacing styles that would apply to the wrapper:

```css
wp-block > * {
	margin: inherit;
	max-width: inherit;
	width: inherit;
}
```

I'm not sure that's enough for every theme, this would need wider testing and some strategy to keep compatibility with existing theme and possibly plugin styles.

**Comment by luisherranz** [comment]
Should it inherit everything like this? 

```css
wp-block > * {
  all: inherit;
}
```

Or just a few rules?

It'd be great to have a CSS expert look at this.
